/// Flutter icons ContactIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ContactIcons
///      fonts:
///       - asset: fonts/ContactIcons.ttf
///
/// 
/// * Zocial, Copyright (C) 2012 by Sam Collins
///         Author:    Sam Collins
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  http://zocial.smcllns.com/
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class ContactIcons {
  ContactIcons._();

  static const _kFontFam = 'ContactIcons';

  static const IconData gmail = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData twitter = IconData(0xf099, fontFamily: _kFontFam);
  static const IconData github = IconData(0xf113, fontFamily: _kFontFam);
  static const IconData linkedin_squared = IconData(0xf30c, fontFamily: _kFontFam);
}
